import React from "react";
import "./Welcome.css";
import Eye from "../Eye";

const Welcome = React.forwardRef((props, ref) => {
    return <>

        <div className="welcome-container section-container">
            <div className="welcome-content">
                <h2 className="section-title" ref={ref}>WELCOME</h2>
                <div className="section-desc">
                    <p>Welcome to Clitopia—home of psychedelic vulvas, standing bold, funky and proud.<br/>
                        This is a land of diversity, self acceptance, freedom and love.
                    </p>
                    <p>Clitizens pop into existence from synthetic NFT embryos generated by you!<br/>
                        Rare genetic mutations make each Clitopian citizen distinctly unique. 
                    </p>
                    <p>Generate and collect Clitopia NFTs<br/>
                        By doing so, you’re supporting the growing vulva community and donating to a good cause. (see NGOs)
                    </p>
                </div>
            </div>
        </div>
        <Eye />
    </>
});

Welcome.displayName = 'Welcome';

export default Welcome;