import React from "react";
import Bg_Pink from "../../assets/img/bg-pink-1.png";
import "./About.css";
import Eye from "../Eye";

const About = ({about}) => {
    return <>
    
        <div className="about-container section-container">
            <div className="about-content">
                <h2 className="section-title" ref={about}>ABOUT CLITOPIA</h2>
                <div className="section-desc">
                    <p>Welcome to Clitopia, home of the free range psychedelic vulvas. A land of diversity, self acceptance, freedom and love and all the wonderful words that one can imagine.</p>
                    <p>Clitizens pop into existence from synthetic NFT embryos generated by you! Rare genetic mutations make each Clitopian citizen distinctly unique.</p>
                    <p>Generate and collect Clitopia NFTs</p>
                    <p>By doing so, you’re supporting the growing vulva community, whilst also donating to a good cause.</p>
                </div>
            </div>
        </div>
        <Eye />
    </>
}
export default About;